<form action="<?php /* @escapeNotVerified */ echo $block->getConnectUrl() ?>" method="post" id="connect-form">
    <?= $this->getChildHtml('store_switcher') ?>
    <?= $block->getBlockHtml('formkey')?>
    <div style="clear:both">
        <fieldset class="admin__fieldset">
            <legend class="admin__legend">
                <span><?php /* @escapeNotVerified */ echo __('Use this form to request access data from Styla.') ?></span>
            </legend><br/>
            <div class="admin__field _required field-email">
                <label for="username" class="admin__field-label">
                    <span><?php /* @escapeNotVerified */ echo __('Styla Account Email') ?></span>
                </label>
                <div class="admin__field-control">
                    <input id="email"
                           class="admin__control-text"
                           type="text"
                           name="styla[email]"
                           autofocus
                           value=""
                           data-validate="{required:true}"
                           placeholder="<?php /* @escapeNotVerified */ echo __('email') ?>"
                        />
                </div>
            </div>
            <div class="admin__field _required field-password">
                <label for="login" class="admin__field-label">
                    <span><?php /* @escapeNotVerified */ echo __('Password') ?></span>
                </label>
                <div class="admin__field-control">
                    <input id="login"
                           class="admin__control-text"
                           type="password"
                           name="styla[password]"
                           data-validate="{required:true}"
                           value=""
                           placeholder="<?php /* @escapeNotVerified */ echo __('password') ?>"
                        />
                </div>
            </div>
            <?php if($this->isDeveloperMode()): ?>
                <div class="admin__field">
                    <div>
                        <h3><?= __('Developer Mode Connection URL override') ?></h3>
                        <span><?= __('If filled, will override the default API url used for connecting to Styla.') ?></span><br/>
                        <i><span><?= __('Default Url is: ') ?><?= \Styla\Connect2\Model\Styla\Api\Connector::STYLA_API_CONNECTOR_URL_PRODUCTION ?></span></i>
                    </div>
                    <label for="connection_url" class="admin__field-label">
                        <span><?php /* @escapeNotVerified */ echo __('Override Connection Url') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input id="connection_url"
                               class="admin__control-text"
                               type="text"
                               name="connection_url"
                               value=""
                               placeholder="<?php /* @escapeNotVerified */ echo __('override connection url (can be empty)') ?>"
                            />
                    </div>
                </div>
            <?php endif ?>
            <div class="actions">
                <button
                    <?php $block->getUiId(); ?>
                    class="action-connect action-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Connect to Styla') ?></span>
                </button>
            </div>
        </fieldset>
    </div>
</form>
<script>
    require(["jquery","mage/mage"],function($){
       $('#connect-form').mage('form').mage('validation');
    });
</script>
